if(EXISTS "/home/lofi/ctc-compiler/compiler-runtime/runtime/antlr4_tests[1]_tests.cmake")
  include("/home/lofi/ctc-compiler/compiler-runtime/runtime/antlr4_tests[1]_tests.cmake")
else()
  add_test(antlr4_tests_NOT_BUILT antlr4_tests_NOT_BUILT)
endif()
